// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /sites/{site-id}/termStore/sets/{set-id}/children/{term-id}/children/{term-id1}/relations/{relation-id}': Operation<
    '/sites/{site-id}/termStore/sets/{set-id}/children/{term-id}/children/{term-id1}/relations/{relation-id}',
    'delete'
  >;
  /**
   * To indicate which terms are related to the current term as either pinned or reused.
   */
  'GET /sites/{site-id}/termStore/sets/{set-id}/children/{term-id}/children/{term-id1}/relations': Operation<
    '/sites/{site-id}/termStore/sets/{set-id}/children/{term-id}/children/{term-id1}/relations',
    'get'
  >;
  /**
   * To indicate which terms are related to the current term as either pinned or reused.
   */
  'GET /sites/{site-id}/termStore/sets/{set-id}/children/{term-id}/children/{term-id1}/relations/{relation-id}': Operation<
    '/sites/{site-id}/termStore/sets/{set-id}/children/{term-id}/children/{term-id1}/relations/{relation-id}',
    'get'
  >;
  /**
   */
  'PATCH /sites/{site-id}/termStore/sets/{set-id}/children/{term-id}/children/{term-id1}/relations/{relation-id}': Operation<
    '/sites/{site-id}/termStore/sets/{set-id}/children/{term-id}/children/{term-id1}/relations/{relation-id}',
    'patch'
  >;
  /**
   */
  'POST /sites/{site-id}/termStore/sets/{set-id}/children/{term-id}/children/{term-id1}/relations': Operation<
    '/sites/{site-id}/termStore/sets/{set-id}/children/{term-id}/children/{term-id1}/relations',
    'post'
  >;
}
