// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /solutions/backupRestore/siteProtectionUnitsBulkAdditionJobs/{siteProtectionUnitsBulkAdditionJob-id}': Operation<
    '/solutions/backupRestore/siteProtectionUnitsBulkAdditionJobs/{siteProtectionUnitsBulkAdditionJob-id}',
    'delete'
  >;
  /**
   */
  'GET /solutions/backupRestore/siteProtectionUnitsBulkAdditionJobs': Operation<
    '/solutions/backupRestore/siteProtectionUnitsBulkAdditionJobs',
    'get'
  >;
  /**
   */
  'GET /solutions/backupRestore/siteProtectionUnitsBulkAdditionJobs/{siteProtectionUnitsBulkAdditionJob-id}': Operation<
    '/solutions/backupRestore/siteProtectionUnitsBulkAdditionJobs/{siteProtectionUnitsBulkAdditionJob-id}',
    'get'
  >;
  /**
   */
  'PATCH /solutions/backupRestore/siteProtectionUnitsBulkAdditionJobs/{siteProtectionUnitsBulkAdditionJob-id}': Operation<
    '/solutions/backupRestore/siteProtectionUnitsBulkAdditionJobs/{siteProtectionUnitsBulkAdditionJob-id}',
    'patch'
  >;
  /**
   */
  'POST /solutions/backupRestore/siteProtectionUnitsBulkAdditionJobs': Operation<
    '/solutions/backupRestore/siteProtectionUnitsBulkAdditionJobs',
    'post'
  >;
}
