// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /sites/{site-id}/lists/{list-id}/columns/{columnDefinition-id}': Operation<
    '/sites/{site-id}/lists/{list-id}/columns/{columnDefinition-id}',
    'delete'
  >;
  /**
   * Get the collection of columns represented as columnDefinition resources in a list.
   */
  'GET /sites/{site-id}/lists/{list-id}/columns': Operation<
    '/sites/{site-id}/lists/{list-id}/columns',
    'get'
  >;
  /**
   * The collection of field definitions for this list.
   */
  'GET /sites/{site-id}/lists/{list-id}/columns/{columnDefinition-id}': Operation<
    '/sites/{site-id}/lists/{list-id}/columns/{columnDefinition-id}',
    'get'
  >;
  /**
   */
  'PATCH /sites/{site-id}/lists/{list-id}/columns/{columnDefinition-id}': Operation<
    '/sites/{site-id}/lists/{list-id}/columns/{columnDefinition-id}',
    'patch'
  >;
  /**
   * Create a column for a list with a request that specifies a columnDefinition.
   */
  'POST /sites/{site-id}/lists/{list-id}/columns': Operation<
    '/sites/{site-id}/lists/{list-id}/columns',
    'post'
  >;
}
