// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * The source column for the content type column.
   */
  'GET /sites/{site-id}/lists/{list-id}/columns/{columnDefinition-id}/sourceColumn': Operation<
    '/sites/{site-id}/lists/{list-id}/columns/{columnDefinition-id}/sourceColumn',
    'get'
  >;
}
