// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /sites/{site-id}/termStores/{store-id}/sets/{set-id}': Operation<
    '/sites/{site-id}/termStores/{store-id}/sets/{set-id}',
    'delete'
  >;
  /**
   * Collection of all sets available in the term store. This relationship can only be used to load a specific term set.
   */
  'GET /sites/{site-id}/termStores/{store-id}/sets': Operation<
    '/sites/{site-id}/termStores/{store-id}/sets',
    'get'
  >;
  /**
   * Collection of all sets available in the term store. This relationship can only be used to load a specific term set.
   */
  'GET /sites/{site-id}/termStores/{store-id}/sets/{set-id}': Operation<
    '/sites/{site-id}/termStores/{store-id}/sets/{set-id}',
    'get'
  >;
  /**
   */
  'PATCH /sites/{site-id}/termStores/{store-id}/sets/{set-id}': Operation<
    '/sites/{site-id}/termStores/{store-id}/sets/{set-id}',
    'patch'
  >;
  /**
   */
  'POST /sites/{site-id}/termStores/{store-id}/sets': Operation<
    '/sites/{site-id}/termStores/{store-id}/sets',
    'post'
  >;
}
