// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /chats/{chat-id}/messages/{chatMessage-id}': Operation<
    '/chats/{chat-id}/messages/{chatMessage-id}',
    'delete'
  >;
  /**
   * Retrieve the list of messages in a chat. This method supports federation. To list chat messages in application context, the request must be made from the tenant that the channel owner belongs to (represented by the tenantId property on the channel).
   */
  'GET /chats/{chat-id}/messages': Operation<'/chats/{chat-id}/messages', 'get'>;
  /**
   * Retrieve a single message or a message reply in a channel or a chat.
   */
  'GET /chats/{chat-id}/messages/{chatMessage-id}': Operation<
    '/chats/{chat-id}/messages/{chatMessage-id}',
    'get'
  >;
  /**
   */
  'PATCH /chats/{chat-id}/messages/{chatMessage-id}': Operation<
    '/chats/{chat-id}/messages/{chatMessage-id}',
    'patch'
  >;
  /**
   * Send a new chatMessage in the specified chat. This API can&#x27;t create a new chat; you must use the list chats method to retrieve the ID of an existing chat before you can create a chat message.
   */
  'POST /chats/{chat-id}/messages': Operation<'/chats/{chat-id}/messages', 'post'>;
}
