// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Add or sync a copy of a published content type from the content type hub to a target site or a list. This method is part of the content type publishing changes to optimize the syncing of published content types to sites and lists, effectively switching from a &#x27;push everywhere&#x27; to &#x27;pull as needed&#x27; approach. The method allows users to pull content types directly from the content type hub to a site or list. For more information, see contentType: getCompatibleHubContentTypes and the blog post Syntex Product Updates – August 2021.
   */
  'POST /sites/{site-id}/lists/{list-id}/contentTypes/addCopyFromContentTypeHub': Operation<
    '/sites/{site-id}/lists/{list-id}/contentTypes/addCopyFromContentTypeHub',
    'post'
  >;
}
