// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Associate a published content type present in a content type hub with a list of hub sites.
   */
  'POST /sites/{site-id}/lists/{list-id}/contentTypes/{contentType-id}/associateWithHubSites': Operation<
    '/sites/{site-id}/lists/{list-id}/contentTypes/{contentType-id}/associateWithHubSites',
    'post'
  >;
}
