// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * The collection of content types that are ancestors of this content type.
   */
  'GET /sites/{site-id}/lists/{list-id}/contentTypes/{contentType-id}/baseTypes': Operation<
    '/sites/{site-id}/lists/{list-id}/contentTypes/{contentType-id}/baseTypes',
    'get'
  >;
  /**
   * The collection of content types that are ancestors of this content type.
   */
  'GET /sites/{site-id}/lists/{list-id}/contentTypes/{contentType-id}/baseTypes/{contentType-id1}': Operation<
    '/sites/{site-id}/lists/{list-id}/contentTypes/{contentType-id}/baseTypes/{contentType-id1}',
    'get'
  >;
}
