// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Parent contentType from which this content type is derived.
   */
  'GET /sites/{site-id}/lists/{list-id}/contentTypes/{contentType-id}/base': Operation<
    '/sites/{site-id}/lists/{list-id}/contentTypes/{contentType-id}/base',
    'get'
  >;
}
