// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /sites/{site-id}/lists/{list-id}/contentTypes/{contentType-id}': Operation<
    '/sites/{site-id}/lists/{list-id}/contentTypes/{contentType-id}',
    'delete'
  >;
  /**
   * Get the collection of contentType resources in a list.
   */
  'GET /sites/{site-id}/lists/{list-id}/contentTypes': Operation<
    '/sites/{site-id}/lists/{list-id}/contentTypes',
    'get'
  >;
  /**
   * The collection of content types present in this list.
   */
  'GET /sites/{site-id}/lists/{list-id}/contentTypes/{contentType-id}': Operation<
    '/sites/{site-id}/lists/{list-id}/contentTypes/{contentType-id}',
    'get'
  >;
  /**
   */
  'PATCH /sites/{site-id}/lists/{list-id}/contentTypes/{contentType-id}': Operation<
    '/sites/{site-id}/lists/{list-id}/contentTypes/{contentType-id}',
    'patch'
  >;
  /**
   */
  'POST /sites/{site-id}/lists/{list-id}/contentTypes': Operation<
    '/sites/{site-id}/lists/{list-id}/contentTypes',
    'post'
  >;
}
