// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Identity of the user who created the item. Read-only.
   */
  'GET /sites/{site-id}/lists/{list-id}/createdByUser': Operation<
    '/sites/{site-id}/lists/{list-id}/createdByUser',
    'get'
  >;
}
