// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /sites/{site-id}/lists/{list-id}/items/{listItem-id}/versions/{listItemVersion-id}': Operation<
    '/sites/{site-id}/lists/{list-id}/items/{listItem-id}/versions/{listItemVersion-id}',
    'delete'
  >;
  /**
   * SharePoint can be configured to retain the history for list items. Previous versions may be retained for a finite period of time depending on admin settings which may be unique per user or location.
   */
  'GET /sites/{site-id}/lists/{list-id}/items/{listItem-id}/versions': Operation<
    '/sites/{site-id}/lists/{list-id}/items/{listItem-id}/versions',
    'get'
  >;
  /**
   * Retrieve the metadata for a specific version of a ListItem.
   */
  'GET /sites/{site-id}/lists/{list-id}/items/{listItem-id}/versions/{listItemVersion-id}': Operation<
    '/sites/{site-id}/lists/{list-id}/items/{listItem-id}/versions/{listItemVersion-id}',
    'get'
  >;
  /**
   */
  'PATCH /sites/{site-id}/lists/{list-id}/items/{listItem-id}/versions/{listItemVersion-id}': Operation<
    '/sites/{site-id}/lists/{list-id}/items/{listItem-id}/versions/{listItemVersion-id}',
    'patch'
  >;
  /**
   */
  'POST /sites/{site-id}/lists/{list-id}/items/{listItem-id}/versions': Operation<
    '/sites/{site-id}/lists/{list-id}/items/{listItem-id}/versions',
    'post'
  >;
}
