// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /sites/{site-id}/termStore/sets/{set-id}/parentGroup/sets/{set-id1}': Operation<
    '/sites/{site-id}/termStore/sets/{set-id}/parentGroup/sets/{set-id1}',
    'delete'
  >;
  /**
   * All sets under the group in a term [store].
   */
  'GET /sites/{site-id}/termStore/sets/{set-id}/parentGroup/sets': Operation<
    '/sites/{site-id}/termStore/sets/{set-id}/parentGroup/sets',
    'get'
  >;
  /**
   * All sets under the group in a term [store].
   */
  'GET /sites/{site-id}/termStore/sets/{set-id}/parentGroup/sets/{set-id1}': Operation<
    '/sites/{site-id}/termStore/sets/{set-id}/parentGroup/sets/{set-id1}',
    'get'
  >;
  /**
   */
  'PATCH /sites/{site-id}/termStore/sets/{set-id}/parentGroup/sets/{set-id1}': Operation<
    '/sites/{site-id}/termStore/sets/{set-id}/parentGroup/sets/{set-id1}',
    'patch'
  >;
  /**
   */
  'POST /sites/{site-id}/termStore/sets/{set-id}/parentGroup/sets': Operation<
    '/sites/{site-id}/termStore/sets/{set-id}/parentGroup/sets',
    'post'
  >;
}
