// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../common.ts';

export interface Endpoints {
  /**
   */
  'POST /me/calendar/calendarView/{event-id}/exceptionOccurrences/{event-id1}/permanentDelete': Operation<
    '/me/calendar/calendarView/{event-id}/exceptionOccurrences/{event-id1}/permanentDelete',
    'post'
  >;
}
