// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /sites/{site-id}/analytics': Operation<'/sites/{site-id}/analytics', 'delete'>;
  /**
   * Analytics about the view activities that took place on this site.
   */
  'GET /sites/{site-id}/analytics': Operation<'/sites/{site-id}/analytics', 'get'>;
  /**
   */
  'PATCH /sites/{site-id}/analytics': Operation<'/sites/{site-id}/analytics', 'patch'>;
}
