// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'GET /sites/{site-id}/analytics/lastSevenDays': Operation<
    '/sites/{site-id}/analytics/lastSevenDays',
    'get'
  >;
}
