// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /sites/{site-id}/columns/{columnDefinition-id}': Operation<
    '/sites/{site-id}/columns/{columnDefinition-id}',
    'delete'
  >;
  /**
   * Get the collection of columns represented as columnDefinition resources in a site.
   */
  'GET /sites/{site-id}/columns': Operation<'/sites/{site-id}/columns', 'get'>;
  /**
   * The collection of column definitions reusable across lists under this site.
   */
  'GET /sites/{site-id}/columns/{columnDefinition-id}': Operation<
    '/sites/{site-id}/columns/{columnDefinition-id}',
    'get'
  >;
  /**
   */
  'PATCH /sites/{site-id}/columns/{columnDefinition-id}': Operation<
    '/sites/{site-id}/columns/{columnDefinition-id}',
    'patch'
  >;
  /**
   * Create a column for a site with a request that specifies a columnDefinition.
   */
  'POST /sites/{site-id}/columns': Operation<'/sites/{site-id}/columns', 'post'>;
}
