// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   * Delete an instance of a workforceIntegration.
   */
  'DELETE /teamwork/workforceIntegrations/{workforceIntegration-id}': Operation<
    '/teamwork/workforceIntegrations/{workforceIntegration-id}',
    'delete'
  >;
  /**
   * Retrieve a list of workforceIntegration objects.
   */
  'GET /teamwork/workforceIntegrations': Operation<'/teamwork/workforceIntegrations', 'get'>;
  /**
   * Retrieve the properties and relationships of a workforceIntegration object.
   */
  'GET /teamwork/workforceIntegrations/{workforceIntegration-id}': Operation<
    '/teamwork/workforceIntegrations/{workforceIntegration-id}',
    'get'
  >;
  /**
   * Update the properties of a workforceIntegration object.
   */
  'PATCH /teamwork/workforceIntegrations/{workforceIntegration-id}': Operation<
    '/teamwork/workforceIntegrations/{workforceIntegration-id}',
    'patch'
  >;
  /**
   * Create a new workforceIntegration object.
   */
  'POST /teamwork/workforceIntegrations': Operation<'/teamwork/workforceIntegrations', 'post'>;
}
