// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'POST /me/calendarView/{event-id}/permanentDelete': Operation<
    '/me/calendarView/{event-id}/permanentDelete',
    'post'
  >;
}
