// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * The content stream
   */
  'GET /sites/{site-id}/onenote/resources/{onenoteResource-id}/content': Operation<
    '/sites/{site-id}/onenote/resources/{onenoteResource-id}/content',
    'get'
  >;
  /**
   * The content stream
   */
  'PUT /sites/{site-id}/onenote/resources/{onenoteResource-id}/content': Operation<
    '/sites/{site-id}/onenote/resources/{onenoteResource-id}/content',
    'put'
  >;
}
