// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /sites/{site-id}/onenote/resources/{onenoteResource-id}': Operation<
    '/sites/{site-id}/onenote/resources/{onenoteResource-id}',
    'delete'
  >;
  /**
   * The image and other file resources in OneNote pages. Getting a resources collection isn&#x27;t supported, but you can get the binary content of a specific resource. Read-only. Nullable.
   */
  'GET /sites/{site-id}/onenote/resources': Operation<'/sites/{site-id}/onenote/resources', 'get'>;
  /**
   * The image and other file resources in OneNote pages. Getting a resources collection isn&#x27;t supported, but you can get the binary content of a specific resource. Read-only. Nullable.
   */
  'GET /sites/{site-id}/onenote/resources/{onenoteResource-id}': Operation<
    '/sites/{site-id}/onenote/resources/{onenoteResource-id}',
    'get'
  >;
  /**
   */
  'PATCH /sites/{site-id}/onenote/resources/{onenoteResource-id}': Operation<
    '/sites/{site-id}/onenote/resources/{onenoteResource-id}',
    'patch'
  >;
  /**
   */
  'POST /sites/{site-id}/onenote/resources': Operation<
    '/sites/{site-id}/onenote/resources',
    'post'
  >;
}
