// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../../common.ts';

export interface Endpoints {
  /**
   * Postpone a reminder for an event in a user calendar until a new time.
   */
  'POST /me/calendars/{calendar-id}/calendarView/{event-id}/exceptionOccurrences/{event-id1}/instances/{event-id2}/snoozeReminder': Operation<
    '/me/calendars/{calendar-id}/calendarView/{event-id}/exceptionOccurrences/{event-id1}/instances/{event-id2}/snoozeReminder',
    'post'
  >;
}
