// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   * Follow a user&#x27;s site or multiple sites.
   */
  'POST /sites/add': Operation<'/sites/add', 'post'>;
}
