// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   * The default drive (document library) for this site.
   */
  'GET /sites/{site-id}/drive': Operation<'/sites/{site-id}/drive', 'get'>;
}
