// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   * The collection of drives (document libraries) under this site.
   */
  'GET /sites/{site-id}/drives': Operation<'/sites/{site-id}/drives', 'get'>;
  /**
   * The collection of drives (document libraries) under this site.
   */
  'GET /sites/{site-id}/drives/{drive-id}': Operation<'/sites/{site-id}/drives/{drive-id}', 'get'>;
}
