// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   */
  'GET /sites/{site-id}/externalColumns': Operation<'/sites/{site-id}/externalColumns', 'get'>;
  /**
   */
  'GET /sites/{site-id}/externalColumns/{columnDefinition-id}': Operation<
    '/sites/{site-id}/externalColumns/{columnDefinition-id}',
    'get'
  >;
}
