// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   * Search across a SharePoint tenant for sites that match keywords provided. The only property that works for sorting is createdDateTime. The search filter is a free text search that uses multiple properties when retrieving the search results.
   */
  'GET /sites': Operation<'/sites', 'get'>;
  /**
   * Retrieve properties and relationships for a site resource.
A site resource represents a team site in SharePoint.
   */
  'GET /sites/{site-id}': Operation<'/sites/{site-id}', 'get'>;
  /**
   */
  'PATCH /sites/{site-id}': Operation<'/sites/{site-id}', 'patch'>;
}
