// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   * List all available sites in an organization. Specific filter criteria and query options are also supported and described below: In addition, you can use a $search query against the /sites collection to find sites matching given keywords.
If you want to list all sites across all geographies, refer to getAllSites. For more guidance about building applications that use site discovery for scanning purposes, see Best practices for discovering files and detecting changes at scale.
   */
  'GET /sites': Operation<'/sites', 'get'>;
  /**
   * Retrieve properties and relationships for a site resource.
A site resource represents a team site in SharePoint.
   */
  'GET /sites/{site-id}': Operation<'/sites/{site-id}', 'get'>;
  /**
   */
  'PATCH /sites/{site-id}': Operation<'/sites/{site-id}', 'patch'>;
}
