// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   * Used to address any item contained in this site. This collection can&#x27;t be enumerated.
   */
  'GET /sites/{site-id}/items': Operation<'/sites/{site-id}/items', 'get'>;
  /**
   * Used to address any item contained in this site. This collection can&#x27;t be enumerated.
   */
  'GET /sites/{site-id}/items/{baseItem-id}': Operation<
    '/sites/{site-id}/items/{baseItem-id}',
    'get'
  >;
}
