// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /sites/{site-id}/operations/{richLongRunningOperation-id}': Operation<
    '/sites/{site-id}/operations/{richLongRunningOperation-id}',
    'delete'
  >;
  /**
   * Get a list of rich long-running operations associated with a site.
   */
  'GET /sites/{site-id}/operations': Operation<'/sites/{site-id}/operations', 'get'>;
  /**
   * Get the status of a rich long-running operation on a site or a list.
   */
  'GET /sites/{site-id}/operations/{richLongRunningOperation-id}': Operation<
    '/sites/{site-id}/operations/{richLongRunningOperation-id}',
    'get'
  >;
  /**
   */
  'PATCH /sites/{site-id}/operations/{richLongRunningOperation-id}': Operation<
    '/sites/{site-id}/operations/{richLongRunningOperation-id}',
    'patch'
  >;
  /**
   */
  'POST /sites/{site-id}/operations': Operation<'/sites/{site-id}/operations', 'post'>;
}
