// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   * Unfollow a user&#x27;s site or multiple sites.
   */
  'POST /sites/remove': Operation<'/sites/remove', 'post'>;
}
