// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   * Get a collection of subsites defined for a site.
   */
  'GET /sites/{site-id}/sites': Operation<'/sites/{site-id}/sites', 'get'>;
  /**
   * The collection of the sub-sites under this site.
   */
  'GET /sites/{site-id}/sites/{site-id1}': Operation<'/sites/{site-id}/sites/{site-id1}', 'get'>;
}
