// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /sites/{site-id}/termStore/groups/{group-id}/sets/{set-id}/children/{term-id}/children/{term-id1}': Operation<
    '/sites/{site-id}/termStore/groups/{group-id}/sets/{set-id}/children/{term-id}/children/{term-id1}',
    'delete'
  >;
  /**
   * Children of current term.
   */
  'GET /sites/{site-id}/termStore/groups/{group-id}/sets/{set-id}/children/{term-id}/children': Operation<
    '/sites/{site-id}/termStore/groups/{group-id}/sets/{set-id}/children/{term-id}/children',
    'get'
  >;
  /**
   * Children of current term.
   */
  'GET /sites/{site-id}/termStore/groups/{group-id}/sets/{set-id}/children/{term-id}/children/{term-id1}': Operation<
    '/sites/{site-id}/termStore/groups/{group-id}/sets/{set-id}/children/{term-id}/children/{term-id1}',
    'get'
  >;
  /**
   */
  'PATCH /sites/{site-id}/termStore/groups/{group-id}/sets/{set-id}/children/{term-id}/children/{term-id1}': Operation<
    '/sites/{site-id}/termStore/groups/{group-id}/sets/{set-id}/children/{term-id}/children/{term-id1}',
    'patch'
  >;
  /**
   */
  'POST /sites/{site-id}/termStore/groups/{group-id}/sets/{set-id}/children/{term-id}/children': Operation<
    '/sites/{site-id}/termStore/groups/{group-id}/sets/{set-id}/children/{term-id}/children',
    'post'
  >;
}
