// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../../common.ts';

export interface Endpoints {
  /**
   * Accept the specified event in a user calendar.
   */
  'POST /me/calendar/events/{event-id}/exceptionOccurrences/{event-id1}/instances/{event-id2}/accept': Operation<
    '/me/calendar/events/{event-id}/exceptionOccurrences/{event-id1}/instances/{event-id2}/accept',
    'post'
  >;
}
