// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../common.ts';

export interface Endpoints {
  /**
   * Delete a version of a document set in a list.
   */
  'DELETE /sites/{site-id}/lists/{list-id}/items/{listItem-id}/documentSetVersions/{documentSetVersion-id}': Operation<
    '/sites/{site-id}/lists/{list-id}/items/{listItem-id}/documentSetVersions/{documentSetVersion-id}',
    'delete'
  >;
  /**
   * Get a list of the versions of a document set item in a list.
   */
  'GET /sites/{site-id}/lists/{list-id}/items/{listItem-id}/documentSetVersions': Operation<
    '/sites/{site-id}/lists/{list-id}/items/{listItem-id}/documentSetVersions',
    'get'
  >;
  /**
   * Read the properties and relationships of a documentSetVersion object.
   */
  'GET /sites/{site-id}/lists/{list-id}/items/{listItem-id}/documentSetVersions/{documentSetVersion-id}': Operation<
    '/sites/{site-id}/lists/{list-id}/items/{listItem-id}/documentSetVersions/{documentSetVersion-id}',
    'get'
  >;
  /**
   */
  'PATCH /sites/{site-id}/lists/{list-id}/items/{listItem-id}/documentSetVersions/{documentSetVersion-id}': Operation<
    '/sites/{site-id}/lists/{list-id}/items/{listItem-id}/documentSetVersions/{documentSetVersion-id}',
    'patch'
  >;
  /**
   * Create a new version of a document set item in a list.
   */
  'POST /sites/{site-id}/lists/{list-id}/items/{listItem-id}/documentSetVersions': Operation<
    '/sites/{site-id}/lists/{list-id}/items/{listItem-id}/documentSetVersions',
    'post'
  >;
}
