// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../common.ts';

export interface Endpoints {
  /**
   */
  'GET /me/calendars/{calendar-id}/events/{event-id}/exceptionOccurrences': Operation<
    '/me/calendars/{calendar-id}/events/{event-id}/exceptionOccurrences',
    'get'
  >;
  /**
   */
  'GET /me/calendars/{calendar-id}/events/{event-id}/exceptionOccurrences/{event-id1}': Operation<
    '/me/calendars/{calendar-id}/events/{event-id}/exceptionOccurrences/{event-id1}',
    'get'
  >;
}
