// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /users/{user-id}/presence': Operation<'/users/{user-id}/presence', 'delete'>;
  /**
   * Set a presence status message for a user. An optional expiration date and time can be supplied.
   */
  'GET /users/{user-id}/presence': Operation<'/users/{user-id}/presence', 'get'>;
  /**
   */
  'PATCH /users/{user-id}/presence': Operation<'/users/{user-id}/presence', 'patch'>;
}
