// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Delete a set object.
   */
  'DELETE /sites/{site-id}/termStore/sets/{set-id}': Operation<
    '/sites/{site-id}/termStore/sets/{set-id}',
    'delete'
  >;
  /**
   * Read the properties and relationships of a set object.
   */
  'GET /sites/{site-id}/termStore/sets': Operation<'/sites/{site-id}/termStore/sets', 'get'>;
  /**
   * Read the properties and relationships of a set object.
   */
  'GET /sites/{site-id}/termStore/sets/{set-id}': Operation<
    '/sites/{site-id}/termStore/sets/{set-id}',
    'get'
  >;
  /**
   * Update the properties of a set object.
   */
  'PATCH /sites/{site-id}/termStore/sets/{set-id}': Operation<
    '/sites/{site-id}/termStore/sets/{set-id}',
    'patch'
  >;
  /**
   * Create a new set object.
   */
  'POST /sites/{site-id}/termStore/sets': Operation<'/sites/{site-id}/termStore/sets', 'post'>;
}
