import { MessageEntity } from './message-entity';

export type AIMessageEntity = MessageEntity & {
  /**
   * Indicate that the content was generated by AI.
   */
  additionalType?: ('AIGeneratedContent' | Omit<string, 'AIGeneratedContent'>)[];
};
