import type { EndpointRequest, Operation } from './../types/common.ts';

export interface IEndpoints {
  'DELETE /auditLogs/customSecurityAttributeAudits/{customSecurityAttributeAudit-id}': Operation<
    '/auditLogs/customSecurityAttributeAudits/{customSecurityAttributeAudit-id}',
    'delete'
  >;
  'GET /auditLogs/customSecurityAttributeAudits': Operation<
    '/auditLogs/customSecurityAttributeAudits',
    'get'
  >;
  'GET /auditLogs/customSecurityAttributeAudits/{customSecurityAttributeAudit-id}': Operation<
    '/auditLogs/customSecurityAttributeAudits/{customSecurityAttributeAudit-id}',
    'get'
  >;
  'PATCH /auditLogs/customSecurityAttributeAudits/{customSecurityAttributeAudit-id}': Operation<
    '/auditLogs/customSecurityAttributeAudits/{customSecurityAttributeAudit-id}',
    'patch'
  >;
  'POST /auditLogs/customSecurityAttributeAudits': Operation<
    '/auditLogs/customSecurityAttributeAudits',
    'post'
  >;
}

/**
 * `DELETE /auditLogs/customSecurityAttributeAudits/{customSecurityAttributeAudit-id}`
 *
 */
export function del(
  params?: IEndpoints['DELETE /auditLogs/customSecurityAttributeAudits/{customSecurityAttributeAudit-id}']['parameters']
): EndpointRequest<
  IEndpoints['DELETE /auditLogs/customSecurityAttributeAudits/{customSecurityAttributeAudit-id}']['response']
> {
  return {
    ver: 'beta',
    method: 'delete',
    path: '/auditLogs/customSecurityAttributeAudits/{customSecurityAttributeAudit-id}',
    paramDefs: [
      { name: 'If-Match', in: 'header' },
      { name: 'customSecurityAttributeAudit-id', in: 'path' },
    ],
    params,
  };
}

/**
 * `GET /auditLogs/customSecurityAttributeAudits`
 *
 * Get the list of audit logs generated by activities related to custom security attribute management in Microsoft Entra ID.
 */
export function list(
  params?: IEndpoints['GET /auditLogs/customSecurityAttributeAudits']['parameters']
): EndpointRequest<IEndpoints['GET /auditLogs/customSecurityAttributeAudits']['response']> {
  return {
    ver: 'beta',
    method: 'get',
    path: '/auditLogs/customSecurityAttributeAudits',
    paramDefs: [
      { name: '$top', in: 'query' },
      { name: '$skip', in: 'query' },
      { name: '$search', in: 'query' },
      { name: '$filter', in: 'query' },
      { name: '$count', in: 'query' },
      { name: '$orderby', in: 'query' },
      { name: '$select', in: 'query' },
      { name: '$expand', in: 'query' },
    ],
    params,
  };
}

/**
 * `GET /auditLogs/customSecurityAttributeAudits/{customSecurityAttributeAudit-id}`
 *
 * Represents a custom security attribute audit log.
 */
export function get(
  params?: IEndpoints['GET /auditLogs/customSecurityAttributeAudits/{customSecurityAttributeAudit-id}']['parameters']
): EndpointRequest<
  IEndpoints['GET /auditLogs/customSecurityAttributeAudits/{customSecurityAttributeAudit-id}']['response']
> {
  return {
    ver: 'beta',
    method: 'get',
    path: '/auditLogs/customSecurityAttributeAudits/{customSecurityAttributeAudit-id}',
    paramDefs: [
      { name: '$select', in: 'query' },
      { name: '$expand', in: 'query' },
      { name: 'customSecurityAttributeAudit-id', in: 'path' },
    ],
    params,
  };
}

/**
 * `PATCH /auditLogs/customSecurityAttributeAudits/{customSecurityAttributeAudit-id}`
 *
 */
export function update(
  body: IEndpoints['PATCH /auditLogs/customSecurityAttributeAudits/{customSecurityAttributeAudit-id}']['body'],
  params?: IEndpoints['PATCH /auditLogs/customSecurityAttributeAudits/{customSecurityAttributeAudit-id}']['parameters']
): EndpointRequest<
  IEndpoints['PATCH /auditLogs/customSecurityAttributeAudits/{customSecurityAttributeAudit-id}']['response']
> {
  return {
    ver: 'beta',
    method: 'patch',
    path: '/auditLogs/customSecurityAttributeAudits/{customSecurityAttributeAudit-id}',
    paramDefs: [{ name: 'customSecurityAttributeAudit-id', in: 'path' }],
    params,
    body,
  };
}

/**
 * `POST /auditLogs/customSecurityAttributeAudits`
 *
 */
export function create(
  body: IEndpoints['POST /auditLogs/customSecurityAttributeAudits']['body'],
  params?: IEndpoints['POST /auditLogs/customSecurityAttributeAudits']['parameters']
): EndpointRequest<IEndpoints['POST /auditLogs/customSecurityAttributeAudits']['response']> {
  return {
    ver: 'beta',
    method: 'post',
    path: '/auditLogs/customSecurityAttributeAudits',
    paramDefs: [],
    params,
    body,
  };
}
