// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /sites/{site-id}/termStore': Operation<'/sites/{site-id}/termStore', 'delete'>;
  /**
   * Read the properties and relationships of a store object.
   */
  'GET /sites/{site-id}/termStore': Operation<'/sites/{site-id}/termStore', 'get'>;
  /**
   * Update the properties of a store object.
   */
  'PATCH /sites/{site-id}/termStore': Operation<'/sites/{site-id}/termStore', 'patch'>;
}
