// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /teams/{team-id}/channels/{channel-id}/allMembers/{conversationMember-id}': Operation<
    '/teams/{team-id}/channels/{channel-id}/allMembers/{conversationMember-id}',
    'delete'
  >;
  /**
   * Get a list of all members in a channel. It supports all types of channels. In the case of shared channels, it includes all cross-tenant and cross-team members in a channel.
   */
  'GET /teams/{team-id}/channels/{channel-id}/allMembers': Operation<
    '/teams/{team-id}/channels/{channel-id}/allMembers',
    'get'
  >;
  /**
   * A collection of membership records associated with the channel, including both direct and indirect members of shared channels.
   */
  'GET /teams/{team-id}/channels/{channel-id}/allMembers/{conversationMember-id}': Operation<
    '/teams/{team-id}/channels/{channel-id}/allMembers/{conversationMember-id}',
    'get'
  >;
  /**
   */
  'PATCH /teams/{team-id}/channels/{channel-id}/allMembers/{conversationMember-id}': Operation<
    '/teams/{team-id}/channels/{channel-id}/allMembers/{conversationMember-id}',
    'patch'
  >;
  /**
   */
  'POST /teams/{team-id}/channels/{channel-id}/allMembers': Operation<
    '/teams/{team-id}/channels/{channel-id}/allMembers',
    'post'
  >;
}
