// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../../../../common.ts';

export interface Endpoints {
  /**
   * The [set] in which the relation is relevant.
   */
  'GET /sites/{site-id}/termStores/{store-id}/sets/{set-id}/parentGroup/sets/{set-id1}/terms/{term-id}/relations/{relation-id}/set': Operation<
    '/sites/{site-id}/termStores/{store-id}/sets/{set-id}/parentGroup/sets/{set-id1}/terms/{term-id}/relations/{relation-id}/set',
    'get'
  >;
}
