// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Delete a group object in a term [store].
   */
  'DELETE /sites/{site-id}/termStore/groups/{group-id}': Operation<
    '/sites/{site-id}/termStore/groups/{group-id}',
    'delete'
  >;
  /**
   * Get a list of group objects in a term store.
   */
  'GET /sites/{site-id}/termStore/groups': Operation<'/sites/{site-id}/termStore/groups', 'get'>;
  /**
   * Read the properties and relationships of a term store group object.
   */
  'GET /sites/{site-id}/termStore/groups/{group-id}': Operation<
    '/sites/{site-id}/termStore/groups/{group-id}',
    'get'
  >;
  /**
   */
  'PATCH /sites/{site-id}/termStore/groups/{group-id}': Operation<
    '/sites/{site-id}/termStore/groups/{group-id}',
    'patch'
  >;
  /**
   * Create a new group object in a term store.
   */
  'POST /sites/{site-id}/termStore/groups': Operation<'/sites/{site-id}/termStore/groups', 'post'>;
}
