// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /me/calendar/events/{event-id}/instances/{event-id1}/exceptionOccurrences/{event-id2}/extensions/{extension-id}': Operation<
    '/me/calendar/events/{event-id}/instances/{event-id1}/exceptionOccurrences/{event-id2}/extensions/{extension-id}',
    'delete'
  >;
  /**
   * The collection of open extensions defined for the event. Nullable.
   */
  'GET /me/calendar/events/{event-id}/instances/{event-id1}/exceptionOccurrences/{event-id2}/extensions': Operation<
    '/me/calendar/events/{event-id}/instances/{event-id1}/exceptionOccurrences/{event-id2}/extensions',
    'get'
  >;
  /**
   * The collection of open extensions defined for the event. Nullable.
   */
  'GET /me/calendar/events/{event-id}/instances/{event-id1}/exceptionOccurrences/{event-id2}/extensions/{extension-id}': Operation<
    '/me/calendar/events/{event-id}/instances/{event-id1}/exceptionOccurrences/{event-id2}/extensions/{extension-id}',
    'get'
  >;
  /**
   */
  'PATCH /me/calendar/events/{event-id}/instances/{event-id1}/exceptionOccurrences/{event-id2}/extensions/{extension-id}': Operation<
    '/me/calendar/events/{event-id}/instances/{event-id1}/exceptionOccurrences/{event-id2}/extensions/{extension-id}',
    'patch'
  >;
  /**
   */
  'POST /me/calendar/events/{event-id}/instances/{event-id1}/exceptionOccurrences/{event-id2}/extensions': Operation<
    '/me/calendar/events/{event-id}/instances/{event-id1}/exceptionOccurrences/{event-id2}/extensions',
    'post'
  >;
}
