// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Retrieve the properties and relationships of a notebook object by using its URL path. The location can be user notebooks on Microsoft 365, group notebooks, or SharePoint site-hosted team notebooks on Microsoft 365.
   */
  'POST /sites/{site-id}/onenote/notebooks/getNotebookFromWebUrl': Operation<
    '/sites/{site-id}/onenote/notebooks/getNotebookFromWebUrl',
    'post'
  >;
}
