// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /sites/{site-id}/onenote/notebooks/{notebook-id}': Operation<
    '/sites/{site-id}/onenote/notebooks/{notebook-id}',
    'delete'
  >;
  /**
   * The collection of OneNote notebooks that are owned by the user or group. Read-only. Nullable.
   */
  'GET /sites/{site-id}/onenote/notebooks': Operation<'/sites/{site-id}/onenote/notebooks', 'get'>;
  /**
   * The collection of OneNote notebooks that are owned by the user or group. Read-only. Nullable.
   */
  'GET /sites/{site-id}/onenote/notebooks/{notebook-id}': Operation<
    '/sites/{site-id}/onenote/notebooks/{notebook-id}',
    'get'
  >;
  /**
   */
  'PATCH /sites/{site-id}/onenote/notebooks/{notebook-id}': Operation<
    '/sites/{site-id}/onenote/notebooks/{notebook-id}',
    'patch'
  >;
  /**
   */
  'POST /sites/{site-id}/onenote/notebooks': Operation<
    '/sites/{site-id}/onenote/notebooks',
    'post'
  >;
}
