// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'GET /me/calendarView/{event-id}/exceptionOccurrences': Operation<
    '/me/calendarView/{event-id}/exceptionOccurrences',
    'get'
  >;
  /**
   */
  'GET /me/calendarView/{event-id}/exceptionOccurrences/{event-id1}': Operation<
    '/me/calendarView/{event-id}/exceptionOccurrences/{event-id1}',
    'get'
  >;
}
