export * as policy from './policy';

import type { EndpointRequest, Operation } from './../../types/common.ts';

export interface IEndpoints {
  'DELETE /networkAccess/alerts/{alert-id}': Operation<
    '/networkAccess/alerts/{alert-id}',
    'delete'
  >;
  'GET /networkAccess/alerts': Operation<'/networkAccess/alerts', 'get'>;
  'GET /networkAccess/alerts/{alert-id}': Operation<'/networkAccess/alerts/{alert-id}', 'get'>;
  'PATCH /networkAccess/alerts/{alert-id}': Operation<'/networkAccess/alerts/{alert-id}', 'patch'>;
  'POST /networkAccess/alerts': Operation<'/networkAccess/alerts', 'post'>;
}

/**
 * `DELETE /networkAccess/alerts/{alert-id}`
 *
 */
export function del(
  params?: IEndpoints['DELETE /networkAccess/alerts/{alert-id}']['parameters']
): EndpointRequest<IEndpoints['DELETE /networkAccess/alerts/{alert-id}']['response']> {
  return {
    ver: 'beta',
    method: 'delete',
    path: '/networkAccess/alerts/{alert-id}',
    paramDefs: [
      { name: 'If-Match', in: 'header' },
      { name: 'alert-id', in: 'path' },
    ],
    params,
  };
}

/**
 * `GET /networkAccess/alerts`
 *
 * Get a list of alert objects and their properties for various alerts generated by Global Secure Access (GSA).
 */
export function list(
  params?: IEndpoints['GET /networkAccess/alerts']['parameters']
): EndpointRequest<IEndpoints['GET /networkAccess/alerts']['response']> {
  return {
    ver: 'beta',
    method: 'get',
    path: '/networkAccess/alerts',
    paramDefs: [
      { name: '$top', in: 'query' },
      { name: '$skip', in: 'query' },
      { name: '$search', in: 'query' },
      { name: '$filter', in: 'query' },
      { name: '$count', in: 'query' },
      { name: '$orderby', in: 'query' },
      { name: '$select', in: 'query' },
      { name: '$expand', in: 'query' },
    ],
    params,
  };
}

/**
 * `GET /networkAccess/alerts/{alert-id}`
 *
 */
export function get(
  params?: IEndpoints['GET /networkAccess/alerts/{alert-id}']['parameters']
): EndpointRequest<IEndpoints['GET /networkAccess/alerts/{alert-id}']['response']> {
  return {
    ver: 'beta',
    method: 'get',
    path: '/networkAccess/alerts/{alert-id}',
    paramDefs: [
      { name: '$select', in: 'query' },
      { name: '$expand', in: 'query' },
      { name: 'alert-id', in: 'path' },
    ],
    params,
  };
}

/**
 * `PATCH /networkAccess/alerts/{alert-id}`
 *
 */
export function update(
  body: IEndpoints['PATCH /networkAccess/alerts/{alert-id}']['body'],
  params?: IEndpoints['PATCH /networkAccess/alerts/{alert-id}']['parameters']
): EndpointRequest<IEndpoints['PATCH /networkAccess/alerts/{alert-id}']['response']> {
  return {
    ver: 'beta',
    method: 'patch',
    path: '/networkAccess/alerts/{alert-id}',
    paramDefs: [{ name: 'alert-id', in: 'path' }],
    params,
    body,
  };
}

/**
 * `POST /networkAccess/alerts`
 *
 */
export function create(
  body: IEndpoints['POST /networkAccess/alerts']['body'],
  params?: IEndpoints['POST /networkAccess/alerts']['parameters']
): EndpointRequest<IEndpoints['POST /networkAccess/alerts']['response']> {
  return {
    ver: 'beta',
    method: 'post',
    path: '/networkAccess/alerts',
    paramDefs: [],
    params,
    body,
  };
}
