// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /sites/{site-id}/termStore/sets/{set-id}/children/{term-id}': Operation<
    '/sites/{site-id}/termStore/sets/{set-id}/children/{term-id}',
    'delete'
  >;
  /**
   * Get the first level children of a [set] or [term] resource using the children navigation property.
   */
  'GET /sites/{site-id}/termStore/sets/{set-id}/children': Operation<
    '/sites/{site-id}/termStore/sets/{set-id}/children',
    'get'
  >;
  /**
   * Children terms of set in term [store].
   */
  'GET /sites/{site-id}/termStore/sets/{set-id}/children/{term-id}': Operation<
    '/sites/{site-id}/termStore/sets/{set-id}/children/{term-id}',
    'get'
  >;
  /**
   */
  'PATCH /sites/{site-id}/termStore/sets/{set-id}/children/{term-id}': Operation<
    '/sites/{site-id}/termStore/sets/{set-id}/children/{term-id}',
    'patch'
  >;
  /**
   * Create a new term object.
   */
  'POST /sites/{site-id}/termStore/sets/{set-id}/children': Operation<
    '/sites/{site-id}/termStore/sets/{set-id}/children',
    'post'
  >;
}
