// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /sites/{site-id}/termStores/{store-id}/groups/{group-id}/sets/{set-id}': Operation<
    '/sites/{site-id}/termStores/{store-id}/groups/{group-id}/sets/{set-id}',
    'delete'
  >;
  /**
   * All sets under the group in a term [store].
   */
  'GET /sites/{site-id}/termStores/{store-id}/groups/{group-id}/sets': Operation<
    '/sites/{site-id}/termStores/{store-id}/groups/{group-id}/sets',
    'get'
  >;
  /**
   * All sets under the group in a term [store].
   */
  'GET /sites/{site-id}/termStores/{store-id}/groups/{group-id}/sets/{set-id}': Operation<
    '/sites/{site-id}/termStores/{store-id}/groups/{group-id}/sets/{set-id}',
    'get'
  >;
  /**
   */
  'PATCH /sites/{site-id}/termStores/{store-id}/groups/{group-id}/sets/{set-id}': Operation<
    '/sites/{site-id}/termStores/{store-id}/groups/{group-id}/sets/{set-id}',
    'patch'
  >;
  /**
   */
  'POST /sites/{site-id}/termStores/{store-id}/groups/{group-id}/sets': Operation<
    '/sites/{site-id}/termStores/{store-id}/groups/{group-id}/sets',
    'post'
  >;
}
