// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Clock in to start a timeCard.
   */
  'POST /teams/{team-id}/schedule/timeCards/clockIn': Operation<
    '/teams/{team-id}/schedule/timeCards/clockIn',
    'post'
  >;
}
