// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Confirm a timeCard.
   */
  'POST /teams/{team-id}/schedule/timeCards/{timeCard-id}/confirm': Operation<
    '/teams/{team-id}/schedule/timeCards/{timeCard-id}/confirm',
    'post'
  >;
}
