// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Delete a timeCard instance in a schedule.
   */
  'DELETE /teams/{team-id}/schedule/timeCards/{timeCard-id}': Operation<
    '/teams/{team-id}/schedule/timeCards/{timeCard-id}',
    'delete'
  >;
  /**
   * Retrieve a list of timeCard entries in a schedule.
   */
  'GET /teams/{team-id}/schedule/timeCards': Operation<
    '/teams/{team-id}/schedule/timeCards',
    'get'
  >;
  /**
   * The time cards in the schedule.
   */
  'GET /teams/{team-id}/schedule/timeCards/{timeCard-id}': Operation<
    '/teams/{team-id}/schedule/timeCards/{timeCard-id}',
    'get'
  >;
  /**
   */
  'PATCH /teams/{team-id}/schedule/timeCards/{timeCard-id}': Operation<
    '/teams/{team-id}/schedule/timeCards/{timeCard-id}',
    'patch'
  >;
  /**
   * Create a timeCard instance in a schedule.
   */
  'POST /teams/{team-id}/schedule/timeCards': Operation<
    '/teams/{team-id}/schedule/timeCards',
    'post'
  >;
}
