// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'POST /teams/{team-id}/schedule/timeCards/{timeCard-id}/startBreak': Operation<
    '/teams/{team-id}/schedule/timeCards/{timeCard-id}/startBreak',
    'post'
  >;
}
