// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../../../common.ts';

export interface Endpoints {
  /**
   * The [set] in which the relation is relevant.
   */
  'GET /sites/{site-id}/termStores/{store-id}/sets/{set-id}/terms/{term-id}/children/{term-id1}/relations/{relation-id}/set': Operation<
    '/sites/{site-id}/termStores/{store-id}/sets/{set-id}/terms/{term-id}/children/{term-id1}/relations/{relation-id}/set',
    'get'
  >;
}
