// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../../../../common.ts';

export interface Endpoints {
  /**
   * The to [term] of the relation. The term to which the relationship is defined.
   */
  'GET /sites/{site-id}/termStore/sets/{set-id}/parentGroup/sets/{set-id1}/children/{term-id}/relations/{relation-id}/toTerm': Operation<
    '/sites/{site-id}/termStore/sets/{set-id}/parentGroup/sets/{set-id1}/children/{term-id}/relations/{relation-id}/toTerm',
    'get'
  >;
}
