import type { EndpointRequest, Operation } from './../../types/common.ts';

export interface IEndpoints {
  'DELETE /networkAccess/tls/externalCertificateAuthorityCertificates/{externalCertificateAuthorityCertificate-id}': Operation<
    '/networkAccess/tls/externalCertificateAuthorityCertificates/{externalCertificateAuthorityCertificate-id}',
    'delete'
  >;
  'GET /networkAccess/tls/externalCertificateAuthorityCertificates': Operation<
    '/networkAccess/tls/externalCertificateAuthorityCertificates',
    'get'
  >;
  'GET /networkAccess/tls/externalCertificateAuthorityCertificates/{externalCertificateAuthorityCertificate-id}': Operation<
    '/networkAccess/tls/externalCertificateAuthorityCertificates/{externalCertificateAuthorityCertificate-id}',
    'get'
  >;
  'PATCH /networkAccess/tls/externalCertificateAuthorityCertificates/{externalCertificateAuthorityCertificate-id}': Operation<
    '/networkAccess/tls/externalCertificateAuthorityCertificates/{externalCertificateAuthorityCertificate-id}',
    'patch'
  >;
  'POST /networkAccess/tls/externalCertificateAuthorityCertificates': Operation<
    '/networkAccess/tls/externalCertificateAuthorityCertificates',
    'post'
  >;
}

/**
 * `DELETE /networkAccess/tls/externalCertificateAuthorityCertificates/{externalCertificateAuthorityCertificate-id}`
 *
 * Delete an externalCertificateAuthorityCertificate object.
 */
export function del(
  params?: IEndpoints['DELETE /networkAccess/tls/externalCertificateAuthorityCertificates/{externalCertificateAuthorityCertificate-id}']['parameters']
): EndpointRequest<
  IEndpoints['DELETE /networkAccess/tls/externalCertificateAuthorityCertificates/{externalCertificateAuthorityCertificate-id}']['response']
> {
  return {
    ver: 'beta',
    method: 'delete',
    path: '/networkAccess/tls/externalCertificateAuthorityCertificates/{externalCertificateAuthorityCertificate-id}',
    paramDefs: [
      { name: 'If-Match', in: 'header' },
      { name: 'externalCertificateAuthorityCertificate-id', in: 'path' },
    ],
    params,
  };
}

/**
 * `GET /networkAccess/tls/externalCertificateAuthorityCertificates`
 *
 * Get a list of the externalCertificateAuthorityCertificate objects and their properties.
 */
export function list(
  params?: IEndpoints['GET /networkAccess/tls/externalCertificateAuthorityCertificates']['parameters']
): EndpointRequest<
  IEndpoints['GET /networkAccess/tls/externalCertificateAuthorityCertificates']['response']
> {
  return {
    ver: 'beta',
    method: 'get',
    path: '/networkAccess/tls/externalCertificateAuthorityCertificates',
    paramDefs: [
      { name: '$top', in: 'query' },
      { name: '$skip', in: 'query' },
      { name: '$search', in: 'query' },
      { name: '$filter', in: 'query' },
      { name: '$count', in: 'query' },
      { name: '$orderby', in: 'query' },
      { name: '$select', in: 'query' },
      { name: '$expand', in: 'query' },
    ],
    params,
  };
}

/**
 * `GET /networkAccess/tls/externalCertificateAuthorityCertificates/{externalCertificateAuthorityCertificate-id}`
 *
 * Get a externalCertificateAuthorityCertificate object.
 */
export function get(
  params?: IEndpoints['GET /networkAccess/tls/externalCertificateAuthorityCertificates/{externalCertificateAuthorityCertificate-id}']['parameters']
): EndpointRequest<
  IEndpoints['GET /networkAccess/tls/externalCertificateAuthorityCertificates/{externalCertificateAuthorityCertificate-id}']['response']
> {
  return {
    ver: 'beta',
    method: 'get',
    path: '/networkAccess/tls/externalCertificateAuthorityCertificates/{externalCertificateAuthorityCertificate-id}',
    paramDefs: [
      { name: '$select', in: 'query' },
      { name: '$expand', in: 'query' },
      { name: 'externalCertificateAuthorityCertificate-id', in: 'path' },
    ],
    params,
  };
}

/**
 * `PATCH /networkAccess/tls/externalCertificateAuthorityCertificates/{externalCertificateAuthorityCertificate-id}`
 *
 * Update the properties of an externalCertificateAuthorityCertificate object. This can be used by a GSA admin to upload the generated certificate for GSA. The certificate is generated by signing the downloaded CSR with the customer&#x27;s PKI.
 */
export function update(
  body: IEndpoints['PATCH /networkAccess/tls/externalCertificateAuthorityCertificates/{externalCertificateAuthorityCertificate-id}']['body'],
  params?: IEndpoints['PATCH /networkAccess/tls/externalCertificateAuthorityCertificates/{externalCertificateAuthorityCertificate-id}']['parameters']
): EndpointRequest<
  IEndpoints['PATCH /networkAccess/tls/externalCertificateAuthorityCertificates/{externalCertificateAuthorityCertificate-id}']['response']
> {
  return {
    ver: 'beta',
    method: 'patch',
    path: '/networkAccess/tls/externalCertificateAuthorityCertificates/{externalCertificateAuthorityCertificate-id}',
    paramDefs: [{ name: 'externalCertificateAuthorityCertificate-id', in: 'path' }],
    params,
    body,
  };
}

/**
 * `POST /networkAccess/tls/externalCertificateAuthorityCertificates`
 *
 * Create a new externalCertificateAuthorityCertificate object. This request generates the Certificate Signing Request (CSR) that you download to sign and generate a certificate that you upload to the service using the Update externalCertificateAuthorityCertificate operation.
 */
export function create(
  body: IEndpoints['POST /networkAccess/tls/externalCertificateAuthorityCertificates']['body'],
  params?: IEndpoints['POST /networkAccess/tls/externalCertificateAuthorityCertificates']['parameters']
): EndpointRequest<
  IEndpoints['POST /networkAccess/tls/externalCertificateAuthorityCertificates']['response']
> {
  return {
    ver: 'beta',
    method: 'post',
    path: '/networkAccess/tls/externalCertificateAuthorityCertificates',
    paramDefs: [],
    params,
    body,
  };
}
