// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /sites/{site-id}/termStores/{store-id}': Operation<
    '/sites/{site-id}/termStores/{store-id}',
    'delete'
  >;
  /**
   * The collection of termStores under this site.
   */
  'GET /sites/{site-id}/termStores': Operation<'/sites/{site-id}/termStores', 'get'>;
  /**
   * The collection of termStores under this site.
   */
  'GET /sites/{site-id}/termStores/{store-id}': Operation<
    '/sites/{site-id}/termStores/{store-id}',
    'get'
  >;
  /**
   */
  'PATCH /sites/{site-id}/termStores/{store-id}': Operation<
    '/sites/{site-id}/termStores/{store-id}',
    'patch'
  >;
  /**
   */
  'POST /sites/{site-id}/termStores': Operation<'/sites/{site-id}/termStores', 'post'>;
}
