// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /sites/{site-id}/termStore/sets/{set-id}/parentGroup': Operation<
    '/sites/{site-id}/termStore/sets/{set-id}/parentGroup',
    'delete'
  >;
  /**
   * The parent [group] that contains the set.
   */
  'GET /sites/{site-id}/termStore/sets/{set-id}/parentGroup': Operation<
    '/sites/{site-id}/termStore/sets/{set-id}/parentGroup',
    'get'
  >;
  /**
   */
  'PATCH /sites/{site-id}/termStore/sets/{set-id}/parentGroup': Operation<
    '/sites/{site-id}/termStore/sets/{set-id}/parentGroup',
    'patch'
  >;
}
