// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Grant users access to a link represented by a permission.
   */
  'POST /sites/{site-id}/permissions/{permission-id}/grant': Operation<
    '/sites/{site-id}/permissions/{permission-id}/grant',
    'post'
  >;
}
