// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Delete a permission object on a site.
   */
  'DELETE /sites/{site-id}/permissions/{permission-id}': Operation<
    '/sites/{site-id}/permissions/{permission-id}',
    'delete'
  >;
  /**
   * Get the permission resources from the permissions navigation property on a site.
   */
  'GET /sites/{site-id}/permissions': Operation<'/sites/{site-id}/permissions', 'get'>;
  /**
   * Retrieve the properties and relationships of a permission object on a site.
   */
  'GET /sites/{site-id}/permissions/{permission-id}': Operation<
    '/sites/{site-id}/permissions/{permission-id}',
    'get'
  >;
  /**
   * Update an application permission object on a site.
   */
  'PATCH /sites/{site-id}/permissions/{permission-id}': Operation<
    '/sites/{site-id}/permissions/{permission-id}',
    'patch'
  >;
  /**
   * Create a new permission object on a site.
   */
  'POST /sites/{site-id}/permissions': Operation<'/sites/{site-id}/permissions', 'post'>;
}
