// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Remove a column from a site, a list, or a content type.
   */
  'DELETE /sites/{site-id}/contentTypes/{contentType-id}/columns/{columnDefinition-id}': Operation<
    '/sites/{site-id}/contentTypes/{contentType-id}/columns/{columnDefinition-id}',
    'delete'
  >;
  /**
   * Get the collection of columns represented as columnDefinition resources in a content type.
   */
  'GET /sites/{site-id}/contentTypes/{contentType-id}/columns': Operation<
    '/sites/{site-id}/contentTypes/{contentType-id}/columns',
    'get'
  >;
  /**
   * Retrieve the metadata for a site, a list, or a contentType column.
   */
  'GET /sites/{site-id}/contentTypes/{contentType-id}/columns/{columnDefinition-id}': Operation<
    '/sites/{site-id}/contentTypes/{contentType-id}/columns/{columnDefinition-id}',
    'get'
  >;
  /**
   * Update a site, a list, or a content type column.
   */
  'PATCH /sites/{site-id}/contentTypes/{contentType-id}/columns/{columnDefinition-id}': Operation<
    '/sites/{site-id}/contentTypes/{contentType-id}/columns/{columnDefinition-id}',
    'patch'
  >;
  /**
   * Add a column to a content type in a site, or a list with a request that specifies a columnDefinition.
   */
  'POST /sites/{site-id}/contentTypes/{contentType-id}/columns': Operation<
    '/sites/{site-id}/contentTypes/{contentType-id}/columns',
    'post'
  >;
}
