// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../common.ts';

export interface Endpoints {
  /**
   */
  'POST /me/calendarView/{event-id}/instances/{event-id1}/exceptionOccurrences/{event-id2}/permanentDelete': Operation<
    '/me/calendarView/{event-id}/instances/{event-id1}/exceptionOccurrences/{event-id2}/permanentDelete',
    'post'
  >;
}
