// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Identity of the user who last modified the item. Read-only.
   */
  'GET /sites/{site-id}/lastModifiedByUser': Operation<
    '/sites/{site-id}/lastModifiedByUser',
    'get'
  >;
}
