// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Errors published by a federated service describing a nontransient, service-specific error regarding the properties or link from a user object.  Supports $filter (eq, not, for isResolved and serviceInstance).
   */
  'GET /sites/{site-id}/lastModifiedByUser/serviceProvisioningErrors': Operation<
    '/sites/{site-id}/lastModifiedByUser/serviceProvisioningErrors',
    'get'
  >;
}
