// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /sites/{site-id}/termStores/{store-id}/sets/{set-id}/children/{term-id}/relations/{relation-id}': Operation<
    '/sites/{site-id}/termStores/{store-id}/sets/{set-id}/children/{term-id}/relations/{relation-id}',
    'delete'
  >;
  /**
   * To indicate which terms are related to the current term as either pinned or reused.
   */
  'GET /sites/{site-id}/termStores/{store-id}/sets/{set-id}/children/{term-id}/relations': Operation<
    '/sites/{site-id}/termStores/{store-id}/sets/{set-id}/children/{term-id}/relations',
    'get'
  >;
  /**
   * To indicate which terms are related to the current term as either pinned or reused.
   */
  'GET /sites/{site-id}/termStores/{store-id}/sets/{set-id}/children/{term-id}/relations/{relation-id}': Operation<
    '/sites/{site-id}/termStores/{store-id}/sets/{set-id}/children/{term-id}/relations/{relation-id}',
    'get'
  >;
  /**
   */
  'PATCH /sites/{site-id}/termStores/{store-id}/sets/{set-id}/children/{term-id}/relations/{relation-id}': Operation<
    '/sites/{site-id}/termStores/{store-id}/sets/{set-id}/children/{term-id}/relations/{relation-id}',
    'patch'
  >;
  /**
   */
  'POST /sites/{site-id}/termStores/{store-id}/sets/{set-id}/children/{term-id}/relations': Operation<
    '/sites/{site-id}/termStores/{store-id}/sets/{set-id}/children/{term-id}/relations',
    'post'
  >;
}
