// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Analytics about the view activities that took place on this item.
   */
  'GET /sites/{site-id}/lists/{list-id}/items/{listItem-id}/analytics': Operation<
    '/sites/{site-id}/lists/{list-id}/items/{listItem-id}/analytics',
    'get'
  >;
}
