// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'POST /sites/{site-id}/lists/{list-id}/items/{listItem-id}/createLink': Operation<
    '/sites/{site-id}/lists/{list-id}/items/{listItem-id}/createLink',
    'post'
  >;
}
