// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /sites/{site-id}/lists/{list-id}/items/{listItem-id}/fields': Operation<
    '/sites/{site-id}/lists/{list-id}/items/{listItem-id}/fields',
    'delete'
  >;
  /**
   * The values of the columns set on this list item.
   */
  'GET /sites/{site-id}/lists/{list-id}/items/{listItem-id}/fields': Operation<
    '/sites/{site-id}/lists/{list-id}/items/{listItem-id}/fields',
    'get'
  >;
  /**
   * Update the properties on a listItem.
   */
  'PATCH /sites/{site-id}/lists/{list-id}/items/{listItem-id}/fields': Operation<
    '/sites/{site-id}/lists/{list-id}/items/{listItem-id}/fields',
    'patch'
  >;
}
