// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * Removes an item from a list.
   */
  'DELETE /sites/{site-id}/lists/{list-id}/items/{listItem-id}': Operation<
    '/sites/{site-id}/lists/{list-id}/items/{listItem-id}',
    'delete'
  >;
  /**
   * Get the collection of items in a list.
   */
  'GET /sites/{site-id}/lists/{list-id}/items': Operation<
    '/sites/{site-id}/lists/{list-id}/items',
    'get'
  >;
  /**
   * Returns the metadata for an item in a list.
   */
  'GET /sites/{site-id}/lists/{list-id}/items/{listItem-id}': Operation<
    '/sites/{site-id}/lists/{list-id}/items/{listItem-id}',
    'get'
  >;
  /**
   */
  'PATCH /sites/{site-id}/lists/{list-id}/items/{listItem-id}': Operation<
    '/sites/{site-id}/lists/{list-id}/items/{listItem-id}',
    'patch'
  >;
  /**
   * Create a new listItem in a list.
   */
  'POST /sites/{site-id}/lists/{list-id}/items': Operation<
    '/sites/{site-id}/lists/{list-id}/items',
    'post'
  >;
}
