// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}': Operation<
    '/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}',
    'delete'
  >;
  /**
   * The section groups in all OneNote notebooks that are owned by the user or group.  Read-only. Nullable.
   */
  'GET /sites/{site-id}/onenote/sectionGroups': Operation<
    '/sites/{site-id}/onenote/sectionGroups',
    'get'
  >;
  /**
   * The section groups in all OneNote notebooks that are owned by the user or group.  Read-only. Nullable.
   */
  'GET /sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}': Operation<
    '/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}',
    'get'
  >;
  /**
   */
  'PATCH /sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}': Operation<
    '/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}',
    'patch'
  >;
  /**
   */
  'POST /sites/{site-id}/onenote/sectionGroups': Operation<
    '/sites/{site-id}/onenote/sectionGroups',
    'post'
  >;
}
