// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * The section group that contains the section group. Read-only.
   */
  'GET /sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/parentSectionGroup': Operation<
    '/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/parentSectionGroup',
    'get'
  >;
}
