// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * The section groups in the section. Read-only. Nullable.
   */
  'GET /sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sectionGroups': Operation<
    '/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sectionGroups',
    'get'
  >;
  /**
   * The section groups in the section. Read-only. Nullable.
   */
  'GET /sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sectionGroups/{sectionGroup-id1}': Operation<
    '/sites/{site-id}/onenote/sectionGroups/{sectionGroup-id}/sectionGroups/{sectionGroup-id1}',
    'get'
  >;
}
