// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'POST /me/calendars/{calendar-id}/calendarView/{event-id}/permanentDelete': Operation<
    '/me/calendars/{calendar-id}/calendarView/{event-id}/permanentDelete',
    'post'
  >;
}
