// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /sites/{site-id}/termStores/{store-id}/groups/{group-id}': Operation<
    '/sites/{site-id}/termStores/{store-id}/groups/{group-id}',
    'delete'
  >;
  /**
   * Collection of all groups available in the term store.
   */
  'GET /sites/{site-id}/termStores/{store-id}/groups': Operation<
    '/sites/{site-id}/termStores/{store-id}/groups',
    'get'
  >;
  /**
   * Collection of all groups available in the term store.
   */
  'GET /sites/{site-id}/termStores/{store-id}/groups/{group-id}': Operation<
    '/sites/{site-id}/termStores/{store-id}/groups/{group-id}',
    'get'
  >;
  /**
   */
  'PATCH /sites/{site-id}/termStores/{store-id}/groups/{group-id}': Operation<
    '/sites/{site-id}/termStores/{store-id}/groups/{group-id}',
    'patch'
  >;
  /**
   */
  'POST /sites/{site-id}/termStores/{store-id}/groups': Operation<
    '/sites/{site-id}/termStores/{store-id}/groups',
    'post'
  >;
}
