// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Allows access to the list as a drive resource with driveItems. Only present on document libraries.
   */
  'GET /sites/{site-id}/lists/{list-id}/drive': Operation<
    '/sites/{site-id}/lists/{list-id}/drive',
    'get'
  >;
}
