// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /sites/{site-id}/lists/{list-id}': Operation<
    '/sites/{site-id}/lists/{list-id}',
    'delete'
  >;
  /**
   * Get the collection of lists for a site. Lists with the system facet are hidden by default.
To list them, include system in your $select statement.
   */
  'GET /sites/{site-id}/lists': Operation<'/sites/{site-id}/lists', 'get'>;
  /**
   * Returns the metadata for a list.
   */
  'GET /sites/{site-id}/lists/{list-id}': Operation<'/sites/{site-id}/lists/{list-id}', 'get'>;
  /**
   */
  'PATCH /sites/{site-id}/lists/{list-id}': Operation<'/sites/{site-id}/lists/{list-id}', 'patch'>;
  /**
   * Create a new list in a site.
   */
  'POST /sites/{site-id}/lists': Operation<'/sites/{site-id}/lists', 'post'>;
}
