// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /sites/{site-id}/termStore/groups/{group-id}/sets/{set-id}/terms/{term-id}': Operation<
    '/sites/{site-id}/termStore/groups/{group-id}/sets/{set-id}/terms/{term-id}',
    'delete'
  >;
  /**
   * Read the properties and relationships of a term object.
   */
  'GET /sites/{site-id}/termStore/groups/{group-id}/sets/{set-id}/terms': Operation<
    '/sites/{site-id}/termStore/groups/{group-id}/sets/{set-id}/terms',
    'get'
  >;
  /**
   * Read the properties and relationships of a term object.
   */
  'GET /sites/{site-id}/termStore/groups/{group-id}/sets/{set-id}/terms/{term-id}': Operation<
    '/sites/{site-id}/termStore/groups/{group-id}/sets/{set-id}/terms/{term-id}',
    'get'
  >;
  /**
   */
  'PATCH /sites/{site-id}/termStore/groups/{group-id}/sets/{set-id}/terms/{term-id}': Operation<
    '/sites/{site-id}/termStore/groups/{group-id}/sets/{set-id}/terms/{term-id}',
    'patch'
  >;
  /**
   */
  'POST /sites/{site-id}/termStore/groups/{group-id}/sets/{set-id}/terms': Operation<
    '/sites/{site-id}/termStore/groups/{group-id}/sets/{set-id}/terms',
    'post'
  >;
}
