// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../../common.ts';

export interface Endpoints {
  /**
   * The [set] in which the term is created.
   */
  'GET /sites/{site-id}/termStore/groups/{group-id}/sets/{set-id}/terms/{term-id}/set': Operation<
    '/sites/{site-id}/termStore/groups/{group-id}/sets/{set-id}/terms/{term-id}/set',
    'get'
  >;
}
