// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'POST /sites/{site-id}/onenote/pages/{onenotePage-id}/onenotePatchContent': Operation<
    '/sites/{site-id}/onenote/pages/{onenotePage-id}/onenotePatchContent',
    'post'
  >;
}
