// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   * The section that contains the page. Read-only.
   */
  'GET /sites/{site-id}/onenote/pages/{onenotePage-id}/parentSection': Operation<
    '/sites/{site-id}/onenote/pages/{onenotePage-id}/parentSection',
    'get'
  >;
}
