// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../../common.ts';

export interface Endpoints {
  /**
   * Dismiss a reminder that has been triggered for an event in a user calendar.
   */
  'POST /me/calendar/calendarView/{event-id}/exceptionOccurrences/{event-id1}/instances/{event-id2}/dismissReminder': Operation<
    '/me/calendar/calendarView/{event-id}/exceptionOccurrences/{event-id1}/instances/{event-id2}/dismissReminder',
    'post'
  >;
}
