// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../common.ts';

export interface Endpoints {
  /**
   * Delete a term object.
   */
  'DELETE /sites/{site-id}/termStore/sets/{set-id}/terms/{term-id}': Operation<
    '/sites/{site-id}/termStore/sets/{set-id}/terms/{term-id}',
    'delete'
  >;
  /**
   * All the terms under the set.
   */
  'GET /sites/{site-id}/termStore/sets/{set-id}/terms': Operation<
    '/sites/{site-id}/termStore/sets/{set-id}/terms',
    'get'
  >;
  /**
   * All the terms under the set.
   */
  'GET /sites/{site-id}/termStore/sets/{set-id}/terms/{term-id}': Operation<
    '/sites/{site-id}/termStore/sets/{set-id}/terms/{term-id}',
    'get'
  >;
  /**
   * Update the properties of a term object.
   */
  'PATCH /sites/{site-id}/termStore/sets/{set-id}/terms/{term-id}': Operation<
    '/sites/{site-id}/termStore/sets/{set-id}/terms/{term-id}',
    'patch'
  >;
  /**
   */
  'POST /sites/{site-id}/termStore/sets/{set-id}/terms': Operation<
    '/sites/{site-id}/termStore/sets/{set-id}/terms',
    'post'
  >;
}
