// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Permanently delete a calendar folder and the events that it contains and remove them from the mailbox. For more information about item retention, see Configure deleted item retention and recoverable items quotas.
   */
  'POST /me/calendars/{calendar-id}/permanentDelete': Operation<
    '/me/calendars/{calendar-id}/permanentDelete',
    'post'
  >;
}
