// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   * Returns the user or organizational contact assigned as the user&#x27;s manager. Optionally, you can expand the manager&#x27;s chain up to the root node.
   */
  'GET /me': Operation<'/me', 'get'>;
  /**
   * Update the properties of a user object.
   */
  'PATCH /me': Operation<'/me', 'patch'>;
}
