// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Delete a baseSitePage from the site pages list in a site.
   */
  'DELETE /sites/{site-id}/pages/{baseSitePage-id}': Operation<
    '/sites/{site-id}/pages/{baseSitePage-id}',
    'delete'
  >;
  /**
   * Get the collection of baseSitePage objects from the site pages list in a site. All pages in the site are returned (with pagination). Sort alphabetically by name in ascending order. The following table lists the available subtypes.
   */
  'GET /sites/{site-id}/pages': Operation<'/sites/{site-id}/pages', 'get'>;
  /**
   * Get the metadata for a baseSitePage in the site pages list in a site.
   */
  'GET /sites/{site-id}/pages/{baseSitePage-id}': Operation<
    '/sites/{site-id}/pages/{baseSitePage-id}',
    'get'
  >;
  /**
   */
  'PATCH /sites/{site-id}/pages/{baseSitePage-id}': Operation<
    '/sites/{site-id}/pages/{baseSitePage-id}',
    'patch'
  >;
  /**
   * Create a new sitePage in the site pages list in a site.
   */
  'POST /sites/{site-id}/pages': Operation<'/sites/{site-id}/pages', 'post'>;
}
