// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}': Operation<
    '/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}',
    'delete'
  >;
  /**
   * The section groups in the notebook. Read-only. Nullable.
   */
  'GET /sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups': Operation<
    '/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups',
    'get'
  >;
  /**
   * The section groups in the notebook. Read-only. Nullable.
   */
  'GET /sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}': Operation<
    '/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}',
    'get'
  >;
  /**
   */
  'PATCH /sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}': Operation<
    '/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}',
    'patch'
  >;
  /**
   */
  'POST /sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups': Operation<
    '/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups',
    'post'
  >;
}
