// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../common.ts';

export interface Endpoints {
  /**
   * The content stream, if the item represents a file.
   */
  'GET /sites/{site-id}/lists/{list-id}/items/{listItem-id}/driveItem/content': Operation<
    '/sites/{site-id}/lists/{list-id}/items/{listItem-id}/driveItem/content',
    'get'
  >;
  /**
   * The content stream, if the item represents a file.
   */
  'PUT /sites/{site-id}/lists/{list-id}/items/{listItem-id}/driveItem/content': Operation<
    '/sites/{site-id}/lists/{list-id}/items/{listItem-id}/driveItem/content',
    'put'
  >;
}
