// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../common.ts';

export interface Endpoints {
  /**
   * For document libraries, the driveItem relationship exposes the listItem as a driveItem
   */
  'GET /sites/{site-id}/lists/{list-id}/items/{listItem-id}/driveItem': Operation<
    '/sites/{site-id}/lists/{list-id}/items/{listItem-id}/driveItem',
    'get'
  >;
}
