// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /sites/{site-id}/lists/{list-id}/subscriptions/{subscription-id}': Operation<
    '/sites/{site-id}/lists/{list-id}/subscriptions/{subscription-id}',
    'delete'
  >;
  /**
   * The set of subscriptions on the list.
   */
  'GET /sites/{site-id}/lists/{list-id}/subscriptions': Operation<
    '/sites/{site-id}/lists/{list-id}/subscriptions',
    'get'
  >;
  /**
   * The set of subscriptions on the list.
   */
  'GET /sites/{site-id}/lists/{list-id}/subscriptions/{subscription-id}': Operation<
    '/sites/{site-id}/lists/{list-id}/subscriptions/{subscription-id}',
    'get'
  >;
  /**
   */
  'PATCH /sites/{site-id}/lists/{list-id}/subscriptions/{subscription-id}': Operation<
    '/sites/{site-id}/lists/{list-id}/subscriptions/{subscription-id}',
    'patch'
  >;
  /**
   */
  'POST /sites/{site-id}/lists/{list-id}/subscriptions': Operation<
    '/sites/{site-id}/lists/{list-id}/subscriptions',
    'post'
  >;
}
