// DO NOT EDIT THIS FILE
import type { Operation } from './../common.ts';

export interface Endpoints {
  /**
   * Deletes a user.
   */
  'DELETE /users/{user-id}': Operation<'/users/{user-id}', 'delete'>;
  /**
   * Retrieve a list of user objects.
   */
  'GET /users': Operation<'/users', 'get'>;
  /**
   * Read properties and relationships of the user object.
   */
  'GET /users/{user-id}': Operation<'/users/{user-id}', 'get'>;
  /**
   * Update the properties of a user object.
   */
  'PATCH /users/{user-id}': Operation<'/users/{user-id}', 'patch'>;
  /**
   * Create a new user object.
   */
  'POST /users': Operation<'/users', 'post'>;
}
