// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /sites/{site-id}/analytics/itemActivityStats/{itemActivityStat-id}': Operation<
    '/sites/{site-id}/analytics/itemActivityStats/{itemActivityStat-id}',
    'delete'
  >;
  /**
   */
  'GET /sites/{site-id}/analytics/itemActivityStats': Operation<
    '/sites/{site-id}/analytics/itemActivityStats',
    'get'
  >;
  /**
   */
  'GET /sites/{site-id}/analytics/itemActivityStats/{itemActivityStat-id}': Operation<
    '/sites/{site-id}/analytics/itemActivityStats/{itemActivityStat-id}',
    'get'
  >;
  /**
   */
  'PATCH /sites/{site-id}/analytics/itemActivityStats/{itemActivityStat-id}': Operation<
    '/sites/{site-id}/analytics/itemActivityStats/{itemActivityStat-id}',
    'patch'
  >;
  /**
   */
  'POST /sites/{site-id}/analytics/itemActivityStats': Operation<
    '/sites/{site-id}/analytics/itemActivityStats',
    'post'
  >;
}
