// DO NOT EDIT THIS FILE
import type { Operation } from './../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /sites/{site-id}/onenote/sections/{onenoteSection-id}': Operation<
    '/sites/{site-id}/onenote/sections/{onenoteSection-id}',
    'delete'
  >;
  /**
   * The sections in all OneNote notebooks that are owned by the user or group.  Read-only. Nullable.
   */
  'GET /sites/{site-id}/onenote/sections': Operation<'/sites/{site-id}/onenote/sections', 'get'>;
  /**
   * The sections in all OneNote notebooks that are owned by the user or group.  Read-only. Nullable.
   */
  'GET /sites/{site-id}/onenote/sections/{onenoteSection-id}': Operation<
    '/sites/{site-id}/onenote/sections/{onenoteSection-id}',
    'get'
  >;
  /**
   */
  'PATCH /sites/{site-id}/onenote/sections/{onenoteSection-id}': Operation<
    '/sites/{site-id}/onenote/sections/{onenoteSection-id}',
    'patch'
  >;
  /**
   */
  'POST /sites/{site-id}/onenote/sections': Operation<'/sites/{site-id}/onenote/sections', 'post'>;
}
