// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /sites/{site-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}': Operation<
    '/sites/{site-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}',
    'delete'
  >;
  /**
   * The sections in the notebook. Read-only. Nullable.
   */
  'GET /sites/{site-id}/onenote/notebooks/{notebook-id}/sections': Operation<
    '/sites/{site-id}/onenote/notebooks/{notebook-id}/sections',
    'get'
  >;
  /**
   * The sections in the notebook. Read-only. Nullable.
   */
  'GET /sites/{site-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}': Operation<
    '/sites/{site-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}',
    'get'
  >;
  /**
   */
  'PATCH /sites/{site-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}': Operation<
    '/sites/{site-id}/onenote/notebooks/{notebook-id}/sections/{onenoteSection-id}',
    'patch'
  >;
  /**
   */
  'POST /sites/{site-id}/onenote/notebooks/{notebook-id}/sections': Operation<
    '/sites/{site-id}/onenote/notebooks/{notebook-id}/sections',
    'post'
  >;
}
