// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../../../common.ts';

export interface Endpoints {
  /**
   */
  'POST /me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/exceptionOccurrences/{event-id1}/instances/{event-id2}/permanentDelete': Operation<
    '/me/calendarGroups/{calendarGroup-id}/calendars/{calendar-id}/events/{event-id}/exceptionOccurrences/{event-id1}/instances/{event-id2}/permanentDelete',
    'post'
  >;
}
