// DO NOT EDIT THIS FILE
import type { Operation } from './../../../../../common.ts';

export interface Endpoints {
  /**
   */
  'GET /me/calendar/calendarView/{event-id}/instances/{event-id1}/exceptionOccurrences': Operation<
    '/me/calendar/calendarView/{event-id}/instances/{event-id1}/exceptionOccurrences',
    'get'
  >;
  /**
   */
  'GET /me/calendar/calendarView/{event-id}/instances/{event-id1}/exceptionOccurrences/{event-id2}': Operation<
    '/me/calendar/calendarView/{event-id}/instances/{event-id1}/exceptionOccurrences/{event-id2}',
    'get'
  >;
}
