// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Add a copy of a content type from a site to a list.
   */
  'POST /sites/{site-id}/contentTypes/addCopy': Operation<
    '/sites/{site-id}/contentTypes/addCopy',
    'post'
  >;
}
