// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /sites/{site-id}/contentTypes/{contentType-id}/columnLinks/{columnLink-id}': Operation<
    '/sites/{site-id}/contentTypes/{contentType-id}/columnLinks/{columnLink-id}',
    'delete'
  >;
  /**
   * The collection of columns that are required by this content type.
   */
  'GET /sites/{site-id}/contentTypes/{contentType-id}/columnLinks': Operation<
    '/sites/{site-id}/contentTypes/{contentType-id}/columnLinks',
    'get'
  >;
  /**
   * The collection of columns that are required by this content type.
   */
  'GET /sites/{site-id}/contentTypes/{contentType-id}/columnLinks/{columnLink-id}': Operation<
    '/sites/{site-id}/contentTypes/{contentType-id}/columnLinks/{columnLink-id}',
    'get'
  >;
  /**
   */
  'PATCH /sites/{site-id}/contentTypes/{contentType-id}/columnLinks/{columnLink-id}': Operation<
    '/sites/{site-id}/contentTypes/{contentType-id}/columnLinks/{columnLink-id}',
    'patch'
  >;
  /**
   */
  'POST /sites/{site-id}/contentTypes/{contentType-id}/columnLinks': Operation<
    '/sites/{site-id}/contentTypes/{contentType-id}/columnLinks',
    'post'
  >;
}
