// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Copy a file to a default content location in a content type. The file can then be added as a default file or template via a POST operation.
   */
  'POST /sites/{site-id}/contentTypes/{contentType-id}/copyToDefaultContentLocation': Operation<
    '/sites/{site-id}/contentTypes/{contentType-id}/copyToDefaultContentLocation',
    'post'
  >;
}
