// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   * Publishes a contentType present in the content type hub site.
   */
  'POST /sites/{site-id}/contentTypes/{contentType-id}/publish': Operation<
    '/sites/{site-id}/contentTypes/{contentType-id}/publish',
    'post'
  >;
}
