// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /sites/{site-id}/onenote': Operation<'/sites/{site-id}/onenote', 'delete'>;
  /**
   * Calls the OneNote service for notebook related operations.
   */
  'GET /sites/{site-id}/onenote': Operation<'/sites/{site-id}/onenote', 'get'>;
  /**
   */
  'PATCH /sites/{site-id}/onenote': Operation<'/sites/{site-id}/onenote', 'patch'>;
}
