// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /sites/{site-id}/onenote/operations/{onenoteOperation-id}': Operation<
    '/sites/{site-id}/onenote/operations/{onenoteOperation-id}',
    'delete'
  >;
  /**
   * The status of OneNote operations. Getting an operations collection isn&#x27;t supported, but you can get the status of long-running operations if the Operation-Location header is returned in the response. Read-only. Nullable.
   */
  'GET /sites/{site-id}/onenote/operations': Operation<
    '/sites/{site-id}/onenote/operations',
    'get'
  >;
  /**
   * The status of OneNote operations. Getting an operations collection isn&#x27;t supported, but you can get the status of long-running operations if the Operation-Location header is returned in the response. Read-only. Nullable.
   */
  'GET /sites/{site-id}/onenote/operations/{onenoteOperation-id}': Operation<
    '/sites/{site-id}/onenote/operations/{onenoteOperation-id}',
    'get'
  >;
  /**
   */
  'PATCH /sites/{site-id}/onenote/operations/{onenoteOperation-id}': Operation<
    '/sites/{site-id}/onenote/operations/{onenoteOperation-id}',
    'patch'
  >;
  /**
   */
  'POST /sites/{site-id}/onenote/operations': Operation<
    '/sites/{site-id}/onenote/operations',
    'post'
  >;
}
