// DO NOT EDIT THIS FILE
import type { Operation } from './../../common.ts';

export interface Endpoints {
  /**
   */
  'DELETE /teams/{team-id}/schedule/dayNotes/{dayNote-id}': Operation<
    '/teams/{team-id}/schedule/dayNotes/{dayNote-id}',
    'delete'
  >;
  /**
   * The day notes in the schedule.
   */
  'GET /teams/{team-id}/schedule/dayNotes': Operation<'/teams/{team-id}/schedule/dayNotes', 'get'>;
  /**
   * The day notes in the schedule.
   */
  'GET /teams/{team-id}/schedule/dayNotes/{dayNote-id}': Operation<
    '/teams/{team-id}/schedule/dayNotes/{dayNote-id}',
    'get'
  >;
  /**
   */
  'PATCH /teams/{team-id}/schedule/dayNotes/{dayNote-id}': Operation<
    '/teams/{team-id}/schedule/dayNotes/{dayNote-id}',
    'patch'
  >;
  /**
   */
  'POST /teams/{team-id}/schedule/dayNotes': Operation<
    '/teams/{team-id}/schedule/dayNotes',
    'post'
  >;
}
